--
-- PostgreSQL database dump
--

-- Dumped from database version 14.1
-- Dumped by pg_dump version 14.1

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: additems_id_seq; Type: SEQUENCE; Schema: public; Owner: tpl_1121_6
--

CREATE SEQUENCE public.additems_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.additems_id_seq OWNER TO tpl_1121_6;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: additems; Type: TABLE; Schema: public; Owner: tpl_1121_6
--

CREATE TABLE public.additems (
    id integer DEFAULT nextval('public.additems_id_seq'::regclass) NOT NULL,
    product_id integer,
    user_id integer
);


ALTER TABLE public.additems OWNER TO tpl_1121_6;

--
-- Name: favitems; Type: TABLE; Schema: public; Owner: tpl_1121_6
--

CREATE TABLE public.favitems (
    id integer NOT NULL,
    users_id integer,
    products_id integer
);


ALTER TABLE public.favitems OWNER TO tpl_1121_6;

--
-- Name: favitems_id_seq; Type: SEQUENCE; Schema: public; Owner: tpl_1121_6
--

ALTER TABLE public.favitems ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.favitems_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: products; Type: TABLE; Schema: public; Owner: tpl_1121_6
--

CREATE TABLE public.products (
    id integer NOT NULL,
    category character varying(1000),
    image character varying(1000),
    title character varying(1000),
    description character varying(1000),
    price character varying(1000)
);


ALTER TABLE public.products OWNER TO tpl_1121_6;

--
-- Name: products_id_seq; Type: SEQUENCE; Schema: public; Owner: tpl_1121_6
--

ALTER TABLE public.products ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.products_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users; Type: TABLE; Schema: public; Owner: tpl_1121_6
--

CREATE TABLE public.users (
    id integer NOT NULL,
    first_name character varying(100),
    last_name character varying(100),
    username character varying(100),
    column5 character varying(100)
);


ALTER TABLE public.users OWNER TO tpl_1121_6;

--
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: tpl_1121_6
--

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: additems; Type: TABLE DATA; Schema: public; Owner: tpl_1121_6
--

COPY public.additems (id, product_id, user_id) FROM stdin;
6	1	\N
\.


--
-- Data for Name: favitems; Type: TABLE DATA; Schema: public; Owner: tpl_1121_6
--

COPY public.favitems (id, users_id, products_id) FROM stdin;
\.


--
-- Data for Name: products; Type: TABLE DATA; Schema: public; Owner: tpl_1121_6
--

COPY public.products (id, category, image, title, description, price) FROM stdin;
10	womens clothing	https://global-uploads.webflow.com/5d556af3fe21d65f602dca94/5ef0a58d9879b25096256161_Order%20%23538874%20%7C%20vassallobrittney%40gmail.com%2049.jpg	\N	\N	\N
1	womens clothing	https://global-uploads.webflow.com/5d556af3fe21d65f602dca94/5de6af354d802a5752497fcb_2R3r2xNWnQqZ.png	Sheer Layered Dress	Multi-Layered colorful Dress with sheer and rope fabric.	100.00
5	bags	https://global-uploads.webflow.com/5d556af3fe21d65f602dca94/5de6acfd8bebe9585fd26cfe_aO9nkVJp6pbB.png	\N	\N	\N
9	womens clothing	https://global-uploads.webflow.com/5d556af3fe21d65f602dca94/5de6ac60ee027c7962d3a96e_mk26eMBz6eZP.png	\N	\N	\N
4	womens clothing	https://global-uploads.webflow.com/5d556af3fe21d65f602dca94/5d8a4e692a59ecc68db4e78d_bbfc954e48578303058297c0d2f3d3d9.png	\N	\N	\N
3	jewelry	https://global-uploads.webflow.com/5d556af3fe21d65f602dca94/5d83612d7e28543525d00058_7e5d1fb0b8264ff69c9980ef6e8ae376.png	\N	\N	\N
14	womens clothing	https://global-uploads.webflow.com/5d556af3fe21d65f602dca94/5ef0a1981b18c0d45ca421cf_Order%20%23538882%20%7C%20jamie%40somethingnavy.com%2033.jpg	\N	\N	\N
2	bags	https://global-uploads.webflow.com/5d556af3fe21d65f602dca94/5de6ae2b4aae0acccb82d7e5_weknabKY1gMQ.png	\N	\N	\N
8	jewelry	https://global-uploads.webflow.com/5d556af3fe21d65f602dca94/5de6ac4aee027cc416d39fb4_GoVnqVyb1JLA.png	\N	\N	\N
13	womens clothing	https://global-uploads.webflow.com/5d556af3fe21d65f602dca94/60802432ab03721222789b4b_5.jpg	\N	\N	\N
12	jewelry	https://global-uploads.webflow.com/5d556af3fe21d65f602dca94/5de6af194a5539cc9e2c305d_Kw31E3mD6qYy.jpeg	\N	\N	\N
6	jewelry	https://global-uploads.webflow.com/5d556af3fe21d65f602dca94/5de6abfe57b9c57cf03f15a7_Mab1K0jOrKXm.png	\N	\N	\N
15	jewelry	https://global-uploads.webflow.com/5d556af3fe21d65f602dca94/5ef0ae0c686f2c115016a6c2_Order%20%23538687%20%7C%20press%40anakhouri.com%2010.jpg	\N	\N	\N
11	womens clothing	https://fakestoreapi.com/img/71z3kpMAYsL._AC_UY879_.jpg	\N	\N	\N
7	womens clothing	https://global-uploads.webflow.com/5d556af3fe21d65f602dca94/5d8a55a3d24a611509b1e76e_5b55e4b9301fd60b994bdc0f3b987499.png	\N	\N	\N
\.


--
-- Data for Name: users; Type: TABLE DATA; Schema: public; Owner: tpl_1121_6
--

COPY public.users (id, first_name, last_name, username, column5) FROM stdin;
\.


--
-- Name: additems_id_seq; Type: SEQUENCE SET; Schema: public; Owner: tpl_1121_6
--

SELECT pg_catalog.setval('public.additems_id_seq', 6, true);


--
-- Name: favitems_id_seq; Type: SEQUENCE SET; Schema: public; Owner: tpl_1121_6
--

SELECT pg_catalog.setval('public.favitems_id_seq', 38, true);


--
-- Name: products_id_seq; Type: SEQUENCE SET; Schema: public; Owner: tpl_1121_6
--

SELECT pg_catalog.setval('public.products_id_seq', 1, false);


--
-- Name: users_id_seq; Type: SEQUENCE SET; Schema: public; Owner: tpl_1121_6
--

SELECT pg_catalog.setval('public.users_id_seq', 1, false);


--
-- Name: additems additems_pkey; Type: CONSTRAINT; Schema: public; Owner: tpl_1121_6
--

ALTER TABLE ONLY public.additems
    ADD CONSTRAINT additems_pkey PRIMARY KEY (id);


--
-- Name: products products_pkey; Type: CONSTRAINT; Schema: public; Owner: tpl_1121_6
--

ALTER TABLE ONLY public.products
    ADD CONSTRAINT products_pkey PRIMARY KEY (id);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: tpl_1121_6
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- Name: additems additems_product_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: tpl_1121_6
--

ALTER TABLE ONLY public.additems
    ADD CONSTRAINT additems_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(id);


--
-- Name: additems additems_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: tpl_1121_6
--

ALTER TABLE ONLY public.additems
    ADD CONSTRAINT additems_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: favitems favitems_products_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: tpl_1121_6
--

ALTER TABLE ONLY public.favitems
    ADD CONSTRAINT favitems_products_id_fkey FOREIGN KEY (products_id) REFERENCES public.products(id);


--
-- Name: favitems favitems_users_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: tpl_1121_6
--

ALTER TABLE ONLY public.favitems
    ADD CONSTRAINT favitems_users_id_fkey FOREIGN KEY (users_id) REFERENCES public.users(id);


--
-- PostgreSQL database dump complete
--

